### ISSUE TITLE
Replace Internet Check URL with a more accessible one

### ISSUE THREAD

**Issue by LouieTian0209** [xerolinux/xl-calamares-config#1]
I noticed that in the settings the internet check url in welcome screen is set to `http://google.com`. This is problematic for users living in countries and regions where Google is not accessible (like China), especially since this installation **_requires_** internet connection. Consider changing it to a more accessible website like `bing.com` or `distrowatch.com` so all users can have a consistent experience when installing it.

**Comment by TechXero** [comment]
Sorry for delay, am on vacation...

Done will be fixed n July release. Thanks for heads up ;)
